### ISSUE TITLE
Angular 2 Material & HTML files

### ISSUE THREAD

**Issue by divanvb** [bakharevpavel/generator-electron-humble#1]
Is there a way to use Angular 2 material and instead of using .jade files, use .html files instead?

**Comment by chun-baoluo** [comment]
Right now, no. You have to implement them yourself in a generated project, but I'll add these features to the generator in next releases.

**Comment by chun-baoluo** [comment]
Made next release. Template engine is now optional + html support for webpack's config in 1.2.0. I will add Angular 2 material support soon.

**Comment by chun-baoluo** [comment]
Done. Added material support in 1.3.0.

**Comment by divanvb** [comment]
You're a champion!
