### ISSUE TITLE
Implementing LiveReload

### ISSUE THREAD

**Issue by divanvb** [bakharevpavel/generator-electron-humble#2]
Hey man. Thanks for updating to choose any template engine. I was wondering if implementing LiveReload would be too much to ask for as editing and saving changes would be nice to reflect without having to stop and rerun npm start to check changes.

Thanks :)

**Comment by chun-baoluo** [comment]
Ok, I'll try to implement this. :)

**Comment by chun-baoluo** [comment]
Done. Now every time you run webpack and change output files, electron reloads automatically. Also, generator now uses webpack 2 instead.
