### ISSUE TITLE
UI Framwork options

### ISSUE THREAD

**Issue by divanvb** [bakharevpavel/generator-electron-humble#3]
Hey man, thanks for updating the app to use Material 2. 

Quick question, what do you think of the idea to have options to multiple UI frameworks such as Material-UI(uses react but still compatible with angular 2), Polymer components while still being able to use angular 2 and only using the components from the preferred frameworks?

Regards!

**Comment by chun-baoluo** [comment]
I'll think about it. :)

**Comment by divanvb** [comment]
Hey man. I've gotten my project working with Polymer using [this](https://vaadin.com/docs/-/part/elements/angular2-polymer/ng-cli-webpack.html)

Had to do a few minor changes to make it work so just wanted to state them here if you decide to integrate UI framworks with the generator to work with angular 2

The file path for the bower_components folder should be in the app folder as the default path(had to be changed as the project ends up running from in the app folder and when its built)
.bowerrc
```bower
{
  "directory" : "app/res/bower_components"
}
```

With the step of creating a main-polymer.ts, skip the creation and add the following code to the index.html file within the body tag
```javascript
document.addEventListener('WebComponentsReady', () => {
  require('./main.ts');
});
```

Other than that, I did the rest following the tutorial and got it working.

Just a heads up, @vaadin/angular2-polymer package hasn't yet been updated to the latest version of angular but the repo is constantly updated but when compiling, you'll maybe get a message when adding the items[PolymerElement('paper-input')] to the declarations in app.module.ts, angular will complain about it "being a function" to put it in simple terms but the components still build and displays correctly.

Hope this helps if you decide to do it :)

**Comment by chun-baoluo** [comment]
OK, I finally decided. :) I think I won't implement this, at least not in the near future. For now I prefer not to mix non-angular related components to the generator.
