### ISSUE TITLE
HMR?

### ISSUE THREAD

**Issue by Polyterative** [bakharevpavel/generator-electron-humble#6]
Are there any chances to get angular's HMR working in the boilerplate? 
I've seen some other boilerplates using it (even with electron live), any suggestions on how to implement it?

Thank you

**Comment by chun-baoluo** [comment]
Sorry for the delay. I updated the generator, now HMR is supported in dev mode. You can check it out. :) Just run **npm run build:dev** and then launch generated electron app with **npm run start:dev**.

**Comment by Polyterative** [comment]
That's great news! Thank you!
I'm sure I'm not the only one happy about this.
